apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-0
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: colintao.tencentcloudcr.com/ci/demo
        ports:
        - containerPort: 80
